-- insert into datasets values("SGFood");
-- insert into users values("lcy4869@qq.com","123");
--
-- insert into tasks values(2,1,"lcy4869@qq.com","none");
-- insert into tasks values(2,2,"lcy4869@qq.com","none");
-- insert into tasks values(2,3,"lcy4869@qq.com","none");
-- insert into tasks values(2,4,"lcy4869@qq.com","none");
-- insert into class(dataset_id,class_name) (dataset_id,class(dataset_id,class_name)_name) values("Chinese");
insert into class(dataset_id,class_name) values(2,"Abacus_Seeds");
insert into class(dataset_id,class_name) values(2,"Herbal_Chicken");
insert into class(dataset_id,class_name) values(2,"Ah_boling");
insert into class(dataset_id,class_name) values(2,"Bak_Chang");
insert into class(dataset_id,class_name) values(2,"Bak_Chor_Mee");
insert into class(dataset_id,class_name) values(2,"Bak_Kut_Teh");
insert into class(dataset_id,class_name) values(2,"Ban_Mian");
insert into class(dataset_id,class_name) values(2,"Bao");
insert into class(dataset_id,class_name) values(2,"Beef_Ball_Bee_Hoon");
insert into class(dataset_id,class_name) values(2,"Beef_Kway_Teow");
insert into class(dataset_id,class_name) values(2,"Cantonese_Roasts");
insert into class(dataset_id,class_name) values(2,"Chai_Tow_Kway");
insert into class(dataset_id,class_name) values(2,"Char_Kway_Teow");
insert into class(dataset_id,class_name) values(2,"Chicken_Noodles");
insert into class(dataset_id,class_name) values(2,"Chicken_Rice");
insert into class(dataset_id,class_name) values(2,"Chow_Tau_Foo");
insert into class(dataset_id,class_name) values(2,"Chwee_Jia_Bao");
insert into class(dataset_id,class_name) values(2,"Chwee_Kueh ");
insert into class(dataset_id,class_name) values(2,"Claypot_Rice");
insert into class(dataset_id,class_name) values(2,"Dian_Xin");
insert into class(dataset_id,class_name) values(2,"Drunken_Prawn");
insert into class(dataset_id,class_name) values(2,"Duck_Rice");
insert into class(dataset_id,class_name) values(2,"Fish_Ball");
insert into class(dataset_id,class_name) values(2,"Fish_Head_Bee_Hoon");
insert into class(dataset_id,class_name) values(2,"Fish_Head_Steamboat");
insert into class(dataset_id,class_name) values(2,"Fish_Soup");
insert into class(dataset_id,class_name) values(2,"Foochow_Fish_Ball");
insert into class(dataset_id,class_name) values(2,"Foochow_Oyster_Cake");
insert into class(dataset_id,class_name) values(2,"Fried_Bee_Hoon");
insert into class(dataset_id,class_name) values(2,"Fried_Hokkien_Mee");
insert into class(dataset_id,class_name) values(2,"Hainanese_Kueh");
insert into class(dataset_id,class_name) values(2,"Har_Cheong_Gai");
insert into class(dataset_id,class_name) values(2,"Herbal_Soup");
insert into class(dataset_id,class_name) values(2,"Hor_Fun");
insert into class(dataset_id,class_name) values(2,"Hum_Chim_Peng");
insert into class(dataset_id,class_name) values(2,"Kaya_Toast");
insert into class(dataset_id,class_name) values(2,"Kuay_Chap");
insert into class(dataset_id,class_name) values(2,"Lor_Mai_Fun");
insert into class(dataset_id,class_name) values(2,"Mee_suah");
insert into class(dataset_id,class_name) values(2,"Min_Chiang_Kueh");
insert into class(dataset_id,class_name) values(2,"Muah_Chee");
insert into class(dataset_id,class_name) values(2,"Mutton_Soup");
insert into class(dataset_id,class_name) values(2,"Ngoh_Hiang");
insert into class(dataset_id,class_name) values(2,"Onde_Onde");
insert into class(dataset_id,class_name) values(2,"Or_Luak");
insert into class(dataset_id,class_name) values(2,"Pig's_Brain_Soup");
insert into class(dataset_id,class_name) values(2,"Pig's_Organ_Soup");
insert into class(dataset_id,class_name) values(2,"Pig_Fallopian_Tubes");
insert into class(dataset_id,class_name) values(2,"Popiah");
insert into class(dataset_id,class_name) values(2,"Popiah_Skins");
insert into class(dataset_id,class_name) values(2,"Porridge");
insert into class(dataset_id,class_name) values(2,"Prawn_Mee");
insert into class(dataset_id,class_name) values(2,"Red_Wine_Ginger_Chicken");
insert into class(dataset_id,class_name) values(2,"Soon_Kway");
insert into class(dataset_id,class_name) values(2,"Soya_Bean_Curd");
insert into class(dataset_id,class_name) values(2,"Streamboat");
insert into class(dataset_id,class_name) values(2,"Taiwan_Porridge");
insert into class(dataset_id,class_name) values(2,"Tau_Kwa");
insert into class(dataset_id,class_name) values(2,"Tau_Kwa_Pau");
insert into class(dataset_id,class_name) values(2,"Tau_Sar_Piah");
insert into class(dataset_id,class_name) values(2,"Teochew");
insert into class(dataset_id,class_name) values(2,"Teochew_Kueh");
insert into class(dataset_id,class_name) values(2,"Teochew_Porridge");
insert into class(dataset_id,class_name) values(2,"Ter_Ka");
insert into class(dataset_id,class_name) values(2,"Turtle_Soup");
insert into class(dataset_id,class_name) values(2,"Vegetarian_Bee_Hoon");
insert into class(dataset_id,class_name) values(2,"Wanton_Mee");
insert into class(dataset_id,class_name) values(2,"Yam_Cake");
insert into class(dataset_id,class_name) values(2,"Yong_Tau_Foo");
insert into class(dataset_id,class_name) values(2,"Youtiao");
insert into class(dataset_id,class_name) values(2,"Cross-cultural");
insert into class(dataset_id,class_name) values(2,"Ayam_Buah_Keluak");
insert into class(dataset_id,class_name) values(2,"Black_Pepper_Crab");
insert into class(dataset_id,class_name) values(2,"Cereal_Prawns");
insert into class(dataset_id,class_name) values(2,"Chap_Chye_Rice");
insert into class(dataset_id,class_name) values(2,"Chicken_Curry");
insert into class(dataset_id,class_name) values(2,"Chicken_Wings(BBQ)");
insert into class(dataset_id,class_name) values(2,"Chilli_Crab");
insert into class(dataset_id,class_name) values(2,"Cold_Crab");
insert into class(dataset_id,class_name) values(2,"Crab_Bee_Hoon");
insert into class(dataset_id,class_name) values(2,"Curry_Mee");
insert into class(dataset_id,class_name) values(2,"Cuttlefish_KangKong");
insert into class(dataset_id,class_name) values(2,"Fish_Head_Curry");
insert into class(dataset_id,class_name) values(2,"Fried_Sweet_Potato_Balls");
insert into class(dataset_id,class_name) values(2,"Grilled_Cuttlefish");
insert into class(dataset_id,class_name) values(2,"Grilled_Stingray");
insert into class(dataset_id,class_name) values(2,"Kacang_Phool");
insert into class(dataset_id,class_name) values(2,"Kari_Debal");
insert into class(dataset_id,class_name) values(2,"Kari_Lemak_Ayam");
insert into class(dataset_id,class_name) values(2,"Kueh_Pie_Tee");
insert into class(dataset_id,class_name) values(2,"Laksa");
insert into class(dataset_id,class_name) values(2,"Lor_Mee");
insert into class(dataset_id,class_name) values(2,"Mee_Goreng");
insert into class(dataset_id,class_name) values(2,"Nasi_Briyani");
insert into class(dataset_id,class_name) values(2,"Nasi_Lemak");
insert into class(dataset_id,class_name) values(2,"Oyster_Omelette");
insert into class(dataset_id,class_name) values(2,"Ramen");
insert into class(dataset_id,class_name) values(2,"Rickshaw_Noodles");
insert into class(dataset_id,class_name) values(2,"Roti_John");
insert into class(dataset_id,class_name) values(2,"Sambal_Kangkong");
insert into class(dataset_id,class_name) values(2,"Sambal_Stingray");
insert into class(dataset_id,class_name) values(2,"Satay_Lok_Lok");
insert into class(dataset_id,class_name) values(2,"Tapioca_Cake");
insert into class(dataset_id,class_name) values(2,"Tauhu_Goreng");
insert into class(dataset_id,class_name) values(2,"Tutu_Kueh");
insert into class(dataset_id,class_name) values(2,"kiam_chye_ark");
insert into class(dataset_id,class_name) values(2,"lei_cha_fan");
insert into class(dataset_id,class_name) values(2,"Desserts");
insert into class(dataset_id,class_name) values(2,"Ang_Ku_Kueh");
insert into class(dataset_id,class_name) values(2,"Apom");
insert into class(dataset_id,class_name) values(2,"Bak_Kwa");
insert into class(dataset_id,class_name) values(2,"Cheng_Tng");
insert into class(dataset_id,class_name) values(2,"Custard");
insert into class(dataset_id,class_name) values(2,"Ice_Kacang");
insert into class(dataset_id,class_name) values(2,"Kuih");
insert into class(dataset_id,class_name) values(2,"Or-ni_dessert");
insert into class(dataset_id,class_name) values(2,"Pulut_hitam");
insert into class(dataset_id,class_name) values(2,"Tau_suan");
insert into class(dataset_id,class_name) values(2,"Drink");
insert into class(dataset_id,class_name) values(2,"Bandung");
insert into class(dataset_id,class_name) values(2,"Beer");
insert into class(dataset_id,class_name) values(2,"Chin_Chow_Drink ");
insert into class(dataset_id,class_name) values(2,"Coffe");
insert into class(dataset_id,class_name) values(2,"Fruit_Juice");
insert into class(dataset_id,class_name) values(2,"Lemon_Barley_Drink");
insert into class(dataset_id,class_name) values(2,"Sugar_Cane_Juice");
insert into class(dataset_id,class_name) values(2,"Teh_Halia_Tarik");
insert into class(dataset_id,class_name) values(2,"From_Fruit");
insert into class(dataset_id,class_name) values(2,"Iced_Desserts");
insert into class(dataset_id,class_name) values(2,"Rojak");
insert into class(dataset_id,class_name) values(2,"Sweet_and_Sour_Pork");
insert into class(dataset_id,class_name) values(2,"Fruit");
insert into class(dataset_id,class_name) values(2,"Durian");
insert into class(dataset_id,class_name) values(2,"Jackfruit");
insert into class(dataset_id,class_name) values(2,"Longan");
insert into class(dataset_id,class_name) values(2,"Lychee");
insert into class(dataset_id,class_name) values(2,"Mangosteen");
insert into class(dataset_id,class_name) values(2,"Pineapple");
insert into class(dataset_id,class_name) values(2,"Rambutan");
insert into class(dataset_id,class_name) values(2,"Indian");
insert into class(dataset_id,class_name) values(2,"Appam");
insert into class(dataset_id,class_name) values(2,"Bihun_Goreng");
insert into class(dataset_id,class_name) values(2,"Chapati");
insert into class(dataset_id,class_name) values(2,"Dosa");
insert into class(dataset_id,class_name) values(2,"Mee_Kuah");
insert into class(dataset_id,class_name) values(2,"Murtabak");
insert into class(dataset_id,class_name) values(2,"Nasi_Goreng");
insert into class(dataset_id,class_name) values(2,"Nasi_Padang");
insert into class(dataset_id,class_name) values(2,"Roti_Prata");
insert into class(dataset_id,class_name) values(2,"Satay_bee_hoon");
insert into class(dataset_id,class_name) values(2,"Sup_Kambing");
insert into class(dataset_id,class_name) values(2,"Sup_Tulang");
insert into class(dataset_id,class_name) values(2,"Tandoori");
insert into class(dataset_id,class_name) values(2,"Thosai");
insert into class(dataset_id,class_name) values(2,"Vadai");
insert into class(dataset_id,class_name) values(2,"Malay");
insert into class(dataset_id,class_name) values(2,"Acar");
insert into class(dataset_id,class_name) values(2,"Assam_Pedas");
insert into class(dataset_id,class_name) values(2,"Ayam_Penyet");
insert into class(dataset_id,class_name) values(2,"Bakso");
insert into class(dataset_id,class_name) values(2,"Begedil");
insert into class(dataset_id,class_name) values(2,"Belacan");
insert into class(dataset_id,class_name) values(2,"Curry_Puff");
insert into class(dataset_id,class_name) values(2,"Dendeng_Paru");
insert into class(dataset_id,class_name) values(2,"Epok_Epok");
insert into class(dataset_id,class_name) values(2,"Goreng_Pisang");
insert into class(dataset_id,class_name) values(2,"Gudeg_Putih");
insert into class(dataset_id,class_name) values(2,"Gulai_Daun_Ubi");
insert into class(dataset_id,class_name) values(2,"Ipoh_Hor_Fun");
insert into class(dataset_id,class_name) values(2,"Keropok");
insert into class(dataset_id,class_name) values(2,"Ketupat");
insert into class(dataset_id,class_name) values(2,"Lemak_Siput");
insert into class(dataset_id,class_name) values(2,"Lontong");
insert into class(dataset_id,class_name) values(2,"Lontong_Goreng");
insert into class(dataset_id,class_name) values(2,"Mee_Rebus");
insert into class(dataset_id,class_name) values(2,"Mee_Siam");
insert into class(dataset_id,class_name) values(2,"Otah");
insert into class(dataset_id,class_name) values(2,"Otak-otak");
insert into class(dataset_id,class_name) values(2,"Pecel_Lele");
insert into class(dataset_id,class_name) values(2,"Putu_Piring");
insert into class(dataset_id,class_name) values(2,"Sambal");
insert into class(dataset_id,class_name) values(2,"Satay");
insert into class(dataset_id,class_name) values(2,"Soto_Ayam");
insert into class(dataset_id,class_name) values(2,"Tumpeng");
insert into class(dataset_id,class_name) values(2,"Western_cuisine");
insert into class(dataset_id,class_name) values(2,"Baked_Beans");
insert into class(dataset_id,class_name) values(2,"Bread");
insert into class(dataset_id,class_name) values(2,"Cheese_Fries");
insert into class(dataset_id,class_name) values(2,"Chicken_Chops");
insert into class(dataset_id,class_name) values(2,"Chicken_Pie");
insert into class(dataset_id,class_name) values(2,"Doughnuts");
insert into class(dataset_id,class_name) values(2,"Egg_Tart");
insert into class(dataset_id,class_name) values(2,"Fish_and_Chips");
insert into class(dataset_id,class_name) values(2,"Fried_Chicken_Wings");
insert into class(dataset_id,class_name) values(2,"Hamburger");
insert into class(dataset_id,class_name) values(2,"Hot_Dog");
insert into class(dataset_id,class_name) values(2,"Mixed_Grills");
insert into class(dataset_id,class_name) values(2,"Oxtail_Stew");
insert into class(dataset_id,class_name) values(2,"Pasta");
insert into class(dataset_id,class_name) values(2,"Pies");
insert into class(dataset_id,class_name) values(2,"Pizza");
insert into class(dataset_id,class_name) values(2,"Sausage_Rolls");
insert into class(dataset_id,class_name) values(2,"Steak");
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/boiling.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_174251.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_174256.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_174331.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_174405.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_174415.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_174444.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_174547.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_174643.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_182857.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_182908.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_182928.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_182949.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_183014.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_183030.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_183058.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_183105.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_183110.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_183118.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_183149.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_183210.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_183238.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_183254.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_183324.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_183339.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_183355.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_183408.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_183430.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_183445.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_183447.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_183506.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_183603.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_183626.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_183638.jpg','unlabelled');
-- insert into image values(2,4,'../static/image/Chinese/Ah_boling/IMG_20150831_183710.jpg','unlabelled');
-- --
